# Generated by Django 5.1.3 on 2024-11-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_coustmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='is_coustomer',
            new_name='is_coustmer',
        ),
    ]
