# Generated by Django 5.1.3 on 2024-11-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_rename_is_coustomer_login_is_coustmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
